-   id: 1
    name: Chiropt√®res
    base_url: "chiro/site"
    appId: 100
    img: "img/chiro.png"
    menu:
        -   url: "#/chiro/site"
            label: "Suivi"
            restrict: 2
        -   url: "#/chiro/inventaire"
            label: "Inventaire"
            restrict: 2
        -   url: "#/chiro/validation"
            label: "Validation"
            restrict: 5
-   id: 2
    name: Howto
    base_url: "g/howto/howto/list"
    appId: 1000006
    menu:
        -   url: "#g/howto/howto/list"
            label: "Howto"
            restrict: 1
-   id: 3
    name: Patrimoine bati
    base_url: "patrimoinebati/site"
    appId: 100
    img: "img/bati.png"
    menu:
        -   url: "#/patrimoinebati/site"
            label: "Suivi"
            restrict: 2
#-   id: 2
#    name: flore
#    base_url: "flore/site"
#    appId: 20
#-   id: 3
#    name: eau
#    base_url: "eau/site"
#    appId: 40
#-   id: 4
#    name: cheveche
#    base_url: "cheveche/site"
#    appId: 110
